apiVersion: v1
kind: Namespace
metadata:
  name: listing-bot-consumer
---
apiVersion: v1
kind: Service
metadata:
  namespace: listing-bot-consumer
  name: listing-bot-consumer-svc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    service: listing-bot-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: listing-bot-consumer
  name: listing-bot-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      service: listing-bot-consumer
  template:
    metadata:
      labels:
        service: listing-bot-consumer
    spec:
      restartPolicy: Always
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: "abcd1234!"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://10.0.0.0:3306/MarketBotConfigs?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: marketbots-svc-acct
          image: bananaztech/listing-bot-consumer:latest
          imagePullPolicy: Always
          name: listing-bot-consumer
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 750Mi
              cpu: 250m
            limits:
              memory: 1G
              cpu: 300m
---